/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as Char123LangChar125DocsChar123Char125DotmdRouteImport } from './routes/{-$lang}/docs/{$}[.]md'
import { Route as Char123LangChar125DocsSplatRouteImport } from './routes/{-$lang}/docs/$'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/{-$lang}/',
  path: '/{-$lang}/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125DocsChar123Char125DotmdRoute =
  Char123LangChar125DocsChar123Char125DotmdRouteImport.update({
    id: '/{-$lang}/docs/{$}.md',
    path: '/{-$lang}/docs/{$}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125DocsSplatRoute =
  Char123LangChar125DocsSplatRouteImport.update({
    id: '/{-$lang}/docs/$',
    path: '/{-$lang}/docs/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
  '/{-$lang}/docs/{$}.md': typeof Char123LangChar125DocsChar123Char125DotmdRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
  '/{-$lang}/docs/{$}.md': typeof Char123LangChar125DocsChar123Char125DotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
  '/{-$lang}/docs/{$}.md': typeof Char123LangChar125DocsChar123Char125DotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/{-$lang}/'
    | '/{-$lang}/docs/$'
    | '/{-$lang}/docs/{$}.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/{-$lang}'
    | '/{-$lang}/docs/$'
    | '/{-$lang}/docs/{$}.md'
  id:
    | '__root__'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/{-$lang}/'
    | '/{-$lang}/docs/$'
    | '/{-$lang}/docs/{$}.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125DocsSplatRoute: typeof Char123LangChar125DocsSplatRoute
  Char123LangChar125DocsChar123Char125DotmdRoute: typeof Char123LangChar125DocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/{-$lang}'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/docs/{$}.md': {
      id: '/{-$lang}/docs/{$}.md'
      path: '/{-$lang}/docs/{$}.md'
      fullPath: '/{-$lang}/docs/{$}.md'
      preLoaderRoute: typeof Char123LangChar125DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/docs/$': {
      id: '/{-$lang}/docs/$'
      path: '/{-$lang}/docs/$'
      fullPath: '/{-$lang}/docs/$'
      preLoaderRoute: typeof Char123LangChar125DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  Char123LangChar125DocsSplatRoute: Char123LangChar125DocsSplatRoute,
  Char123LangChar125DocsChar123Char125DotmdRoute:
    Char123LangChar125DocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
